version = 0.1

[default.deploy.parameters]
stack_name = "opulence-wedding-bakes"
resolve_s3 = true
s3_prefix = "opulence-wedding-bakes"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []

[default.global.parameters]
region = "eu-west-2"
